### ISSUE TITLE
Essence of Red Mana and Rage gains for druid

### ISSUE THREAD

**Issue by Kujalla** [jvd33/ClassicThreat#44]
https://github.com/jvd33/ClassicThreat/blob/56226568726428ef4d51d2310192584f1ae787fa/backend/core/models/common.py#L164

Currently using 5 multiplier for both mana and rage gains instead of 0.5 for mana.

Need something to differentiate between resourceChangeType: 0 (mana) and 1 (rage) in the events type: "energize".

(Or for a hack you could just divide the ThreatEvent 'amount' by 10 in those cases at https://github.com/jvd33/ClassicThreat/blob/a46c72d733ec664c20235cc9a9e95e60a46db537/backend/core/models/common.py#L373 or something.)

**Comment by jvd33** [comment]
Good looks. Easy fix, I'll get a change in for this today. Thanks for the issue, appreciate it!

**Comment by jvd33** [comment]
@Kujalla Hey there, I just pushed a new build that appears to have resolved this. I also fixed Faerie Fire resists being counted and improved the accuracy of resource-gain related threat across the board. 

I don't expect it to be 100% issue-free just yet, but it's certainly much, much more accurate now than it was before. Take a peek when you get a chance and let me know how it looks!
