### ISSUE TITLE
Failed to load threat rankings. Please try again later or file a bug report if it persists (WARRIOR)

### ISSUE THREAD

**Issue by HaydenBruinsma** [jvd33/ClassicThreat#45]
Hey I am trying to access the rankings for warriors however it does not load.
The other classes do load though.

**Comment by jvd33** [comment]
Hey, thanks for this. Looks like it's due to site load- my backend was running out of resources. I'm going to look into strategies to be more efficient with said resources, but in the interim I just bumped up the memory on the API host. Looks like everything is working again.
