### ISSUE TITLE
Misses apply bonus threat

### ISSUE THREAD

**Issue by dfherr** [jvd33/ClassicThreat#48]
As far as I can see from https://github.com/jvd33/ClassicThreat/blob/master/backend/core/models/common.py#L113 you add bonus threat based on the SPELL_CAST_SUCCESS event. However, this event is also fired when a SPELL_MISSED event happens (miss, dodge, parry, block) and then inaccurately applies bonus threat.

cheers from libthreat

**Comment by dfherr** [comment]
A nevermind, I saw you are parsing the misses as part of a `damage` event type. 

https://github.com/jvd33/ClassicThreat/blob/master/backend/core/models/common.py#L132

**Comment by jvd33** [comment]
Just commenting to note that a lot of this is due for a refactoring, it was written with no previous xp with the combat log or the wcl API so this is about as hamfisted a solution as it gets.

It seems to work, but I wouldnt be surprised if theres more edge cases so I appreciate the 2nd eye
