### ISSUE TITLE
Unexpected error. Try again later.

### ISSUE THREAD

**Issue by iambryan0** [jvd33/ClassicThreat#57]
**Describe the bug**
Log URL is correct. Username is correct. Still getting an error message for any log or username inputed.

**To Reproduce**
enter a username, enter the corresponding URL. Run.

**Expected behavior**
A "Unexpected error. Try again later." message will be returned.
**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, IE, Edge, Firefox

**Smartphone (please complete the following information):**
 Iphone 8 

**Additional context**
Have seen this issue in the past but was resolved before the next time I used it. Love the program thank you for putting it together and maintaining it for the community. Cheers.

**Comment by jvd33** [comment]
Haven't done any maintenance of any kind on the app in awhile. With a few reports of downtime, I flushed out tons of old data and stabilized the app again. Also added AQ/ZG bosses (that I should've done a long time ago)

Glad you're still getting use out of it. I'll do my best to keep it running + accurate despite not playing Classic any longer
